[package]
name = "spatiub2"
version = "0.1.0"
authors = ["pierre <pierrelarger@gmail.com>"]

[dependencies]
tokio = "0.1.5"
tokio-core = "0.1.17"
mio-uds = "0.6.4"
log = "0.4"
env_logger = "0.5.9"
capnp = "0.8.17"
capnpc = "0.8.9"
futures = "0.2.1"
capnp-futures = "0.1.1"